name: neurobrock2
description: Neurobrock instance, which uses a fine-tuned gpt-3.5-curie
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.2.0


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
dependencies: 
  characters: ^1.3.0
  googleapis_auth: ^1.6.0
  http: ^1.1.0
  nyxx: ^6.2.1
  nyxx_commands: ^6.0.2
